name: Deploy Cosmocloud Backend

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: docker build -t aviral30/cosmocloud_backend .
      - name: Push Docker Image
        run: docker push aviral30/cosmocloud_backend:latest

  
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull Docker Image
        run: docker pull aviral30/cosmocloud_backend:latest
      - name: Delete Existing Container
        run: docker rm -f cosmocloud_backend_container
      - name: Run Docker Container
        run: docker run -d -p 5000:5000 --name cosmocloud_backend_container -e MONGO_PASSWORD='${{ secrets.MONGO_PASSWORD }}' aviral30/cosmocloud_backend:latest